development: &development
  adapter: postgresql
  encoding: unicode
  database: furfromhome_development
  # template     : template0
  pool: 5
  # min_messages : warning

test:
  <<: *development
  database: furfromhome_test

staging: &staging
  <<: *development
  database: furfromhome_staging

production:
  <<: *development
  database: furfromhome_production
